services:
  backend:
    build: ./backend
    ports:
      - "5050:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/asset-management
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  frontend:
    build:
      context: ./MobApp/
      dockerfile: Dockerfile
    ports:
      - "3050:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5050/api

volumes:
  mongo_data:
