services:
  backend:
    build: ./backend
    ports:
      - "5050:5000"
    environment:
      - MONGO_URI=mongodb://admin:Mongo123@mongo:27017/asset-management?authSource=admin
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27018:27017"  # 27018 exposed on host, internal is 27017
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Mongo123

  frontend:
    build:
      context: ./MobApp/
      dockerfile: Dockerfile
    ports:
      - "3050:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5050/api

volumes:
  mongo_data:
